trigger:
    - master
    
    pool:
      vmImage: 'ubuntu-16.04'
    
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      tag: 'latest'
      buildConfiguration: 'Release'
    
    stages:
      - stage: Production
        jobs:
          - job: Restore
            steps:
              - task: DotNetCoreCLI@2
                displayName: 'Restore packages'
                inputs:
                  command: 'restore'
                  restoreArguments: '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
    
          - job: Build
            dependsOn: Restore
            steps:
              - task: DotNetCoreCLI@2
                displayName: 'Build project'
                inputs:
                  command: 'build'
                  projects: |
                    '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
                  configuration: 'Release'
    

    
    # stages:
      - stage: Build
        displayName: Build image
        jobs:  
        - job: Build
          displayName: Build
          pool:
            vmImage: 'ubuntu-latest'
          steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/DockerfileSPA'
              tags: |
                $(tag)
          - task: Docker@2
            displayName: Push an image
            inputs:
              command: push
              containerRegistry: DockerHubConnection
    
    