# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- dev

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  tag: '$(Build.BuildId)'
  # buildConfiguration: 'Release'

stages:
  - stage: Development
    jobs:
      - job: Restore
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore packages'
            inputs:
              command: 'restore'
              restoreArguments: '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'

      - job: Build
        dependsOn: Restore
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              command: 'build'
              projects: 
                '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
              configuration: 'Debug'

# resources:
# - repo: self

# stages:
  - stage: Build
    displayName: Build image
    jobs:  
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/DockerfileSPA'
          tags: |
            $(tag)

  # - stage: Production
  #   jobs:
  #     - job: Restore
  #       steps:
  #         - task: DotNetCoreCLI@2
  #           displayName: 'Restore packages'
  #           inputs:
  #             command: 'restore'

  #     - job: Build
  #       dependsOn: Restore
  #       steps:
  #         - task: DotNetCoreCLI@2
  #           displayName: 'Build project'
  #           inputs:
  #             command: 'build'
  #             configuration: 'Production'

  #     - job: Publish
  #       dependsOn: Build
  #       steps:
  #         - task: PublishBuildArtifacts@1
  #           displayName: 'Publish Artifats'
  #           inputs:
  #             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #             ArtifactName: 'FluppesProj'
  #             publishLocation: 'Container'




