trigger:
- dev

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  tag: '$(Build.BuildId)'
  # buildConfiguration: 'Release'

stages:
  - stage: Development
    jobs:
      - job: Restore
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore packages'
            inputs:
              command: 'restore'
              restoreArguments: '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'

      - job: Build
        dependsOn: Restore
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              command: 'build'
              projects: 
                '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
              configuration: 'Debug'

  - stage: Build
    displayName: Build image
    jobs:  
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/DockerfileAPI'
          repository: 'millegalb/slipways.api'
          tags: |
            $(tag)
