trigger:
- master
    
pool:
  vmImage: 'ubuntu-16.04'
    
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  tag: 'latest'
  buildConfiguration: 'Release'
    
stages:
 - stage: Production
   jobs:
     - job: Restore
       steps:
         - task: DotNetCoreCLI@2
           displayName: 'Restore packages'
           inputs:
             command: 'restore'
             restoreArguments: '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
    
     - job: Build
       dependsOn: Restore
       steps:
         - task: DotNetCoreCLI@2
           displayName: 'Build project'
           inputs:
             command: 'build'
             projects:
               '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
              


  - stage: Docker
    displayName: Build and Publish
    jobs:  
      - job: Build
        displayName: Build and Publish
        steps:
            - task: Docker@2
              inputs:
                containerRegistry: 'DockerHubConnection'
                command: 'login'
            - task: Docker@2
              inputs:
                containerRegistry: 'DockerHubConnection'
                repository: 'millegalb/slipways.api'
                command: 'buildAndPush'
                Dockerfile: '**/DockerfileAPI'
                tags: |
                  $(tag)    
    