# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
    - master
    
    pool:
      vmImage: 'ubuntu-16.04'
    
    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      tag: 'latest'
      buildConfiguration: 'Release'
    
    stages:
      - stage: Production
        jobs:
          - job: Restore
            steps:
              - task: DotNetCoreCLI@2
                displayName: 'Restore packages'
                inputs:
                  command: 'restore'
                  restoreArguments: '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
    
          - job: Build
            dependsOn: Restore
            steps:
              - task: DotNetCoreCLI@2
                displayName: 'Build project'
                inputs:
                  command: 'build'
                  projects: |
                    '$(Build.SourcesDirectory)/BackEnd/Slipways.API/Slipways.API.sln'
                  configuration: 'Release'
    

    
    # stages:
      - stage: Build
        displayName: Build image
        jobs:  
        - job: Build
          displayName: Build
          pool:
            vmImage: 'ubuntu-latest'
          steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: '$(Build.SourcesDirectory)/DockerfileSPA'
              tags: |
                $(tag)
          - task: Docker@2
            displayName: Push an image
            inputs:
              command: push
              containerRegistry: DockerHubConnection
    
      # - stage: Production
      #   jobs:
      #     - job: Restore
      #       steps:
      #         - task: DotNetCoreCLI@2
      #           displayName: 'Restore packages'
      #           inputs:
      #             command: 'restore'
    
      #     - job: Build
      #       dependsOn: Restore
      #       steps:
      #         - task: DotNetCoreCLI@2
      #           displayName: 'Build project'
      #           inputs:
      #             command: 'build'
      #             configuration: 'Production'
    
      #     - job: Publish
      #       dependsOn: Build
      #       steps:
      #         - task: PublishBuildArtifacts@1
      #           displayName: 'Publish Artifats'
      #           inputs:
      #             PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #             ArtifactName: 'FluppesProj'
      #             publishLocation: 'Container'
    
    
    
    
    