version: "3.7"

services:
  slip_api:
    image: millegalb/slip.api:latest
    #healthcheck:
    #    test: ["CMD", "curl", "-f", "http://localhost:8095/api/test"]
    #    interval: 60s
    #    timeout: 5s
    #    retries: 3
    deploy:
        labels:
          - "traefik.enable=true"

          - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"
          - "traefik.http.routers.slipways-api-http.entrypoints=web"
          - "traefik.http.routers.slipways-api-http.rule=Host(`api.slipways.de`)"
          - "traefik.http.routers.slipways-api-http.middlewares=https-only@docker"

          - "traefik.http.routers.slipways-api-https.rule=Host(`api.slipways.de`)"
          - "traefik.http.routers.slipways-api-https.entrypoints=websecure"
          - "traefik.http.routers.slipways-api-https.tls.certresolver=sec"

          - "traefik.http.services.slipways-api-service.loadbalancer.server.port=80"
      replicas: 1
      restart_policy:
        condition: on-failure
    #depends_on:
    #    - sqlserver
    #    - slipways-dataprovider
    networks:
      - skynet
    secrets:
      - db_slip_password
      - key
networks:
  skynet:
    external: true

secrets:
  db_slip_password:
    external: true
  key:
    external: true