name: Publish GraphQL to Docker
on:
  push:
    tags:
      - 'graphQL_v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: millegalb/slipways-graphql
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: DockerfileGraphQL
        source-url: https://nuget.pkg.github.com/Marcel-B/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
